### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by gibberwocky** [jbelyeu/samplot#28]
Hi

I'm getting an error that appears to relate to genomics coordinates but I can't crack it. Can you suggest what issue might be?

`Traceback (most recent call last):
  File "/exports/eddie/scratch/dwragg/myconda/envs/samplot/bin/samplot", line 10, in <module>
    sys.exit(main())
  File "/exports/eddie/scratch/dwragg/myconda/envs/samplot/lib/python3.7/site-packages/samplot/__main__.py", line 31, in main
    args.func(parser)
  File "/exports/eddie/scratch/dwragg/myconda/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 3585, in plot
    options.end_ci,
  File "/exports/eddie/scratch/dwragg/myconda/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 1771, in create_variant_plot
    plot_variant(sv, sv_type, ax, ranges)
  File "/exports/eddie/scratch/dwragg/myconda/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 1695, in plot_variant
    map_genome_point_to_range_points(ranges, sv[0].chrm, sv[0].start),
  File "/exports/eddie/scratch/dwragg/myconda/envs/samplot/lib/python3.7/site-packages/samplot/samplot.py", line 151, in map_genome_point_to_range_points
    / float(ranges[range_hit].end - ranges[range_hit].start)
ZeroDivisionError: float division by zero`

Cheers

D

**Comment by gibberwocky** [comment]
This puzzled me for several hours, but having now posted the issue I think I've identified the problem. The SV is larger than the default plotting range, increasing the window size appeared to solve this. I say 'appeared' because I now have an issue with the GFF file that I didn't have before (KeyError 'Name')...
